import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import UserProvider from "./providers/AppProvider";

import "./globals.css";
import Providers from "./providers/UserProvider";
import { getServerSession } from "next-auth";
import authOptions from "./api/auth/[...nextauth]/authOptions";
import { useSession } from "next-auth/react";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Game",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {

  const session = await getServerSession(authOptions);
  // console.log("session ====> ", session);
  // const session = useSession();
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <UserProvider>
            {children}
          </UserProvider>
        </Providers>
      </body>
    </html>
  );
}